### ISSUE TITLE
Discrepancy with @material-ui/core

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1631]
The purpose of this issue is to **identify misalignment** between the main repository and this one, see what improvement we can bring in any direction.

This issue fits into this effort https://github.com/mui-org/material-ui/issues/19706.

The core idea around why this approach can help bring value:

1. Put constraints in place to maximize the consitency of the developer experience on the whole library (**user side**).
2. Make it easier for an engineer to contribute to the library, as a whole, **no matter which component** we are used to working on. Experimentations should go through small efforts / **RFC** and be rollout at 100% when successful, not scattered between components.
3. Share knowledge, tools, and great practices learned the hard way. Any small incremental improvement to the CI, tests, etc compound. It can be very hard to share and enforce different repositories.

### List of items

- [x] Export default right from the function declaration to increase code density. Meaning, no `export default BasicDatePicker;`.
- [x] Replace usage of `import React, { useState } from 'react';` with `import React as * from 'react'; React.useState`. https://github.com/mui-org/material-ui/pull/19802
- [x] Improve one level deep from:

```diff
-import { Button } from '@material-ui/core';
+import Button from '@material-ui/core/Button';
```

- [x] Remove `.displayName` for component. React dev tools can infer the display name from the name of the function, plus the display names are kept in production, increasing the bundle size and reducing obfuscation. For instance: https://github.com/mui-org/material-ui-pickers/blob/502118dbc268f77ca510bb78d6d588ea96ec4161/lib/src/DateRangePicker/DateRangePickerDay.tsx#L161
- [ ] Add display names when leveraging the `React.createContext()` API. The motivation is explained in https://github.com/mui-org/material-ui/pull/18468. For instance: https://github.com/mui-org/material-ui-pickers/blob/502118dbc268f77ca510bb78d6d588ea96ec4161/lib/src/LocalizationProvider.tsx#L6
- [ ] Always spread the props on the root element if public. always. When not possible, consider breaking the component down into smaller chunks or introducing a `xxxProps` prop. I have seen the following issues. For instance: 
- [x] Migrate from **enzyme** shallow (eww) to enzyme render (good) to **testing-library** (great). This is a work in progress on our side with the core components. We would upgrade the test anytime we find the opportunity, for instance when fixing a bug.
- [ ] Have all the components using [describeConfirmance.js](https://github.com/mui-org/material-ui/blob/e9eb2df4dc87707f47f5383976e9ec7ec6510678/packages/material-ui/src/test-utils/describeConformance.js). This help ensures the API of the component match the common conventions.
- [x] Replace the usage of `<A children={<B />} />` with the idiomatic React way: `<A><B /></A>`. For instance: https://github.com/mui-org/material-ui-pickers/blob/502118dbc268f77ca510bb78d6d588ea96ec4161/lib/src/DatePicker/DatePickerToolbar.tsx#L65-L67
- [x] Name the style rule that is applied to the root element: `root`. For instance: https://github.com/mui-org/material-ui-pickers/blob/502118dbc268f77ca510bb78d6d588ea96ec4161/lib/src/DateRangePicker/DateRangePickerDay.tsx#L124
- [x] There is no need to prefix the style rule with the name of the component. For instance:
https://github.com/mui-org/material-ui-pickers/blob/502118dbc268f77ca510bb78d6d588ea96ec4161/lib/src/views/Calendar/Month.tsx#L62
- [ ] Replace the usage of `mergeRefs` with `useForkRef` (in core/utils). This hook avoided the ref cleanup cycle at each render.
- [ ] Replace the usage of `createDelegatedEventHandler` with `createChainedFunction` (in core/utils). This avoids duplication in the bundle for the same feature. 
- [ ] Always spread props last. For instance: https://github.com/mui-org/material-ui-pickers/blob/502118dbc268f77ca510bb78d6d588ea96ec4161/lib/src/DateRangePicker/DateRangePickerInput.tsx#L120-L123
- [x] Always respect the dependencies chain. For instance: 
- [x] Remove usage of all `.defaultProps`. See https://github.com/mui-org/material-ui/pull/16542 for reference. For instance https://github.com/mui-org/material-ui-pickers/blob/7bed283699ef768936a3ec7c5dc89571492dddd4/lib/src/views/Calendar/Day.tsx#L232

### Already with standalone issues

- [x] #1340, #578, and #1356. Replace the usage of `makeStyles` with `withStyles`.
- [x] #1617. Update the wording of the descriptions of the props to match the style of core. For instance: https://github.com/mui-org/material-ui-pickers/blob/7bed283699ef768936a3ec7c5dc89571492dddd4/lib/src/typings/BasePicker.tsx#L22-L23 Would turn into:
```tsx
  /**
   * If `true`, the picker will be read-only.
   */
  readOnly?: boolean;
```
- [x] #1604. Forward the ref on the root element for all the public components.

If anything is unclear or you would like to start a discussion on the why. Let me know :).

**Comment by dmtrKovalenko** [comment]
There are several points from the list I think pure antipatterns. We could discuss it further.

**Comment by oliviertassinari** [comment]
> We could discuss it further.

@dmtrKovalenko Definitely :). Should we have a call? Otherwise happy to continue the conversation here in the writing (best so we can come back at it in the future) 👌
